#!/bin/sh
if ! [ -x /snap/bin/snapcraft ]; then
    echo "" >&2
    echo "Command '$0' requires the snapcraft snap to be installed." >&2
    echo "Please install it with:" >&2
    echo "" >&2
    echo "snap install snapcraft" >&2
    echo "" >&2
    exit 1
fi
exec /snap/bin/snapcraft "$@"
